dohere|githere: Simplify and format; List dependencies
Also delete old dohere that was kept as backup

diff --git a/bin/dohere b/bin/dohere
--- a/bin/dohere
+++ b/bin/dohere
@@ -1,12 +1,6 @@
 #!/usr/bin/env zsh
-# Make aliases cleaner by passing a '.' to a command if there are no other args
 
-declare cmd="$1"
-shift
-
-if [[ -z "$cmd" ]]; then
-	echo "[dohere] ERROR: No arguments passed"
-	echo
+usage() {
 	echo "DOHERE"
 	echo "\tMake aliases cleaner by adding a '.' in case no arguments are passed"
 	echo
@@ -15,11 +9,17 @@ if [[ -z "$cmd" ]]; then
 	echo
 	echo "\tIf no [arguments] are provided, the <command> is ran as '<command> \$toplevel' if in a repo, or as '<command> .'"
 	echo "\tElse, the [arguments] get passed down and the <command> executed as usual"
+}
 
+declare cmd="$1"
+shift || {
+	echo "[dohere] ERROR: No arguments passed"
+	echo
+	usage
 	exit 1
-fi
+}
 
-if (( $#args == 0 )); then
+if (( $# )); then
 	"$cmd" "$@"
 else
 	"$cmd" "."
